name: AAVE
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        run: npm ci --force
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build:production
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: aave.blockanalitica.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AAVE_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AAVE_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: "build"
      - name: Set cache-control on index.html
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_AAVE_S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_AAVE_S3_SECRET_ACCESS_KEY }}
          source: 's3://aave.blockanalitica.com/index.html'
          dest: 's3://aave.blockanalitica.com/index.html'
          flags: --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl private
      - name: Set cache-control on asset-manifest.json
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_AAVE_S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_AAVE_S3_SECRET_ACCESS_KEY }}
          source: 's3://aave.blockanalitica.com/asset-manifest.json'
          dest: 's3://aave.blockanalitica.com/asset-manifest.json'
          flags: --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/json --acl private
